name: Main PR and Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rspec:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.x

    - name: Test
      timeout-minutes: 2
      run: rake

  rubocop:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.x

    - name: Set up gems
      run: gem install rubocop rubocop-performance --no-document

    - name: Lint
      timeout-minutes: 2
      run: rubocop

  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
