name: Main PR and Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rspec:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true

    - name: Test
      timeout-minutes: 2
      run: bundle exec rake test

  rubocop:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true

    - name: Lint
      timeout-minutes: 2
      run: bundle exec rubocop

  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
